# Generated by Django 4.0 on 2022-02-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='update_ad',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_ad',
            new_name='update_at',
        ),
    ]
